### ISSUE TITLE
[Error Handling] 차예진 22.01.27

### ISSUE THREAD

**Issue by chayezo** [FreeCocktail/FreeCocktail#46]
> ### 어떤 에러인가요?
> semantic-ui를 import 하고 난 후 컴파일 에러

> ### 에러 메시지
> ```bash
> TypeError: Cannot read property 'get' of undefined during rendering of asset asset/inline|data:application/x-font-ttf;charset=utf-8;
> ```
> 
> ### 에러 핸들링 방법
> 열심히 구글링..
> 에러 코드를 넣어 검색했는데 검색 결과가 나오지 않아서 힘들었다.
> 컴파일 하는 데 시간이 오래 걸려서, 컴파일 에러인거 같아 검색어를 수정 후 재검색했더니 나와 비슷한 케이스가 있어서 해결할 수 있었다.
> ```js
> @semantic-ui-react/css-patch 모듈 설치
> ```
> 
> ### 에러 핸들링을 위해 참고한 레퍼런스 링크
> * https://stackoverflow.com/questions/70367443/create-react-app-with-typescript-failing-to-compile-after-importing-semantic-ui
> * https://github.com/Semantic-Org/Semantic-UI-React/issues/4287

**Comment by jungwoo-0530** [comment]
안녕하세요 스프링 부트 공부 중인데요. 토이프로젝트하려고 리엑트 잠깐 공부하는 동안 이 문제 발생했습니다.
말씀해주신 것처럼 했는데 안되길래... 레퍼런스에 있는 첫번째 방법인 semantic.css 19990라인에서 ;을 제거하니깐 되더군요. 정보 감사합니다.
